name = "TAC Units"
prefix = "tacu"
author = "TAC Units Team"
files = [
    "mod.cpp",
    "README.md",
    "logo_tacu_ca.paa",
    "logo_tacu_small_ca.paa"
]
modname = "tac_units"
key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}"

releasebuild = [
    "@zip tac_units_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]

[header_exts]
version = "{{git \"id 8\"}}"

# Binarizer file search compatibility
[scripts.binarizer_link]
steps_windows = [
    "if not exist x\\tacu mkdir x\\tacu",
    "if not exist x\\tacu\\addons mklink /j x\\tacu\\addons addons"
]
steps_linux = [
    # Preparation for Windows Binarizer (run once on Linux for network share compatibility)
    "mkdir -p x/tacu",
    "ln -sr addons x/tacu/addons"
]
