name = "TAC Units"
prefix = "tacu"
author = "TAC Units Team"
files = [
    "mod.cpp",
    "README.md",
    "logo_tacu_ca.paa",
    "logo_tacu_small_ca.paa"
]
modname = "tac_units"
keyname = "{{prefix}}_{{version}}"
signame = "{{prefix}}_{{version}}"

releasebuild = [
    #"@zip tac_units_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]
